### ISSUE TITLE
Switch to re-enable Windows Family Safety features.

### ISSUE THREAD

**Issue by evilbulgarian** [LeDragoX/Win-Debloat-Tools#104]
### Description

Hi, can we please get a switch to re-enable the windows family features. I did comment out the Optimize-TaskScheduler.ps1 which has some of the family safety stuff in it. But I am still not able to see what processes are being used and able to lock down which processes are allowed / not allowed. Thanks!

### Reason

Need the pc to be locked down via family safety for my kids.

**Comment by Techn0core** [comment]
I'm about to reinstall windows to get windows family features back. Did you find any solution? 

I'm not a fan of the way the settings seem to work. It should specifically list everything you are going to disable / remove. There's no checkbox for family safety features, I wonder how many other things did it remove with no explicit setting for it.

**Comment by evilbulgarian** [comment]
Basically comment out Optimize-TaskScheduler.ps1 or pass the revert option to it

**Comment by weirdal3333** [comment]
You really shouldn't rely on Microsoft to keep you kids 'safe' on the internet. It's the equivalent of installing the McAfee free trial to protect yourself from viruses.

The Microsoft 'feature' is really meant to start collecting data on them as soon as possible.
What you should do is make them an offline user account and utilize the features that have already been around since *windows 95* to manage login time and to prevent them from installing crap. If you really want to restrict their access to certain websites, set up a pihole.

**Comment by LeDragoX** [comment]
> I wonder how many other things did it remove with no explicit setting for it.

Huh... I did remove a lot of things, sorry for not making this so customizable as other scripts, but it did disabled the tasks, this is recoverable.

**Comment by LeDragoX** [comment]
Sorry to all parents "spying" on your sons/daughters, I didn't expected this feature to be used, I'm sorry by being so late, this won't happen again with a new option. This will require a new Section to "Scheduled Tasks" on GUI.
