### ISSUE TITLE
Windows explorer, command prompt unresponsible

### ISSUE THREAD

**Issue by ameyakoshti** [LeDragoX/Win-Debloat-Tools#114]
### Describe the Bug

1. Ran "Apply Tweak"
2. Restarted Windows 11

Issue #1
Open File Explorer. I am able to navigate on the left hand panel but as soon as I select a folder, on the right panel I see "Working on it...". File Explorer stays in thie mode till killed.

Issue #2
Through OneCommander, navigated to "OpenTerminalHere" and ran as Administrator. Command prompt is stuck on "Running Admin shell".

Issue #3 
PrintSrn freezes the entire windows including task manager. Have to hard reset the laptop.

Because of issue #2 I am unable to "Undo Tweaks".
Is there any other way to Undo Tweaks?

### How can this issue be reproduced?

Run "Apply Tweaks" on Windows 11.

### Operating System

Windows 11

### Operating System Version

22H2

### Screenshots

Unable to take screenshot since PrintSrc causes the entire system to freeze

**Comment by weirdal3333** [comment]
This sounds like a hardware issue and not an issue with the script. Works fine for me! You may want to check your drive with crystaldiskinfo, and also test your ram.

**Comment by LeDragoX** [comment]
This may be caused by some hardware issue (as @weirdal3333 mentioned) or driver from your laptop missing, I hope it's not related to overhead cause the Power Plan was changed to **High Performance**, this turn up the clocks and speed, at the cost of temperature and fan noises (more perceptible in your case).

It's not normal to get stuck, unless you clicked the Cmd/PowerShell window, as this rename the window to _"Select ..."_ and pause any running command inside it.

About "Undoing" the script, this seems to be a case of corrupt system install, the Repair Windows button should help something, only if that's the case. Another way to solve your problem is if you own an HDD instead of a SSD as Storage, bad blocks may be interrupting your system to run smoothly.

**Comment by LeDragoX** [comment]
Anyway, I took so much time to answer this, and nobody else talked in this comment section about having the same problem. So it seems to be ok if this issue is closed.

**Comment by ameyakoshti** [comment]
Sorry for the late response. I had to use a system restore to get it back to working.
Apprecitate looking into the issue.

**Comment by MahefaAbel** [comment]
I have exactly the same issues (1. Enable to navigate Windows Explorer anymore, 2. PrtSrn freeze all screen) after applying this tweak.
