### ISSUE TITLE
Not good as w4rh4wk scripts

### ISSUE THREAD

**Issue by al1ce23** [LeDragoX/Win-Debloat-Tools#124]
### Description

This software sets up chocolatey and installs thirdparty software without asking if you want that and doesnt have a list of bloatware to uninstall. You just can debloat xbox and msstore. Also why is there an option to install cortana? I want to uninstall that spyware. Dont know if the maintainer really supports debloating of windows ...

Tryed out, doenst helped and doesnt provide an uninstall script - so i reset my windows to get rid of 

### Reason

N/A

**Comment by LeDragoX** [comment]
Okay, you have a lot of good points.
> This software sets up chocolatey and installs thirdparty software without asking if you want that and doesnt have a list of bloatware to uninstall.
1. This caused me trouble too, as for other people, in the develop branch i don't do it automated anymore, and you can enable and disable these Tasks, and of course uninstall chocolatey. (#110)
> Also why is there an option to install cortana?
2. I thought it was a good way to bring back, but even MS doesn't support it now, Cortana is removed by the "Apply Tweaks", I don't leave it on the system.
> I want to uninstall that spyware. Dont know if the maintainer really supports debloating of windows ...
3. If you want someone who is every day spending time on the script, I would like to recommend Chris Titus software, he is doing it in C# library inside Powershell, XAML, and the UI is much more easy to navigate and simple (https://github.com/ChrisTitusTech/winutil).
To be honest, I'm maintaining this to ease the system stress on CPU/RAM and see my system working without any trouble and being the closest to a "minimal" install of Windows.
> Tryed out, doenst helped and doesnt provide an uninstall script - so i reset my windows to get rid of
4. Sorry if this isn't a fully customizable script, i wish i could do that, but I had to do a lot of things from scratch, or maybe a lot of stuff couldn't be as simple as it is right now. Btw, WinForms sucks, and I didn't have the guts to make like Chris' version with Xaml, even because I don't like copying other codes, but instead doing it my way.

**Comment by LeDragoX** [comment]
I'll remove Cortana from the UI, it's really useless.
