### ISSUE TITLE
`Brightness` control stopped working in laptop

### ISSUE THREAD

**Issue by Triplesweet** [LeDragoX/Win-Debloat-Tools#49]
### Describe the Bug

After running the scripts and after a restart my brightness control didn't work, I tried reversing the tweaks from the app but it still didn't work, it was a fresh install of windows 11 

### How can this issue be reproduced?

I just ran the script and after a restart it didn't work

### Operating System

Windows 11

### Operating System Version

from system information,  version 10.0.22000 build 22000

### Date Executed

19/7/2022

**Comment by LeDragoX** [comment]
Hello, i know i'm 2 weeks late, but i'm managing better the time i spent doing this and my graduation monography.

> After running the scripts and after a restart my brightness control didn't work, I tried reversing the tweaks from the app but it still didn't work, it was a fresh install of windows 11


This kinda happened with me before when using an old laptop, i bypassed the advices about **Secure Boot** and **TPM 2.0** to adventure myself doing that, i had no solution but will give a hint.

This is likely of being an driver issue, fresh installs won't came with all manufacturer drivers, so, you need to search the **Manufacturer + Model** name from the laptop and search for it's drivers.

If this don't helps, maybe it's related either to **Graphics driver**, cause that's responsible for giving video on the display.

Then to settle this, the only step the script does that **max out** the brightness control, is because it's changing the Power Plan to the **High Performance** preset, so maybe changing that would help.

**Comment by sr229** [comment]
I don't believe the debloating script has something to do with this, as display controls are provided by the Windows Driver of your OEM, note this also does not affect the functionality of shell as well.
