### ISSUE TITLE
Keeps deleting important system files

### ISSUE THREAD

**Issue by DED0026** [LeDragoX/Win-Debloat-Tools#52]
### Describe the Bug

Xbox stuff is required to play Minecraft now as Microsoft owns it
using the debloater on a fresh un-updated install of windows lead to winget uninstalling
on a seperate install, after using the pc for a while winget fuckin vanished anyway
don't know what to do at this point I'm considering not using this thing anymore
in a previous update save Xbox option didn't even work
services fail to start after getting changed by the debloater don't know how or why
also microsoft live support ass so couldnt reach them
no contact links either so I couldn't get a community to ask questions

### How can this issue be reproduced?

its every time
![image](https://user-images.githubusercontent.com/98061642/182818401-a31bc739-2417-4891-86b7-69130f1c0cb6.png)
how

### Expected behavior?

"a clear and concise description of what you expected to happen"
i expected it not to fuck up my pc i dont know how to explain it

### Operating System

Windows 10

### Operating System Version

21h2

### Date Executed

2022/7/1 y/m/d  

### Screenshots

linked a screenshot in the other textbox

### Logs

i really dont have the logs anymore temp files clear every restart

### Additional Info

fix it please. will be appreciated.

**Comment by DED0026** [comment]
forgive me for being rude
just sick and not wanting to call microsoft support again

**Comment by LeDragoX** [comment]
> Xbox stuff is required to play Minecraft now as Microsoft owns it

You can use the GUI button to "**Install Xbox**", hope that helps, if you clicked to **Remove Xbox**.

> using the debloater on a fresh un-updated install of windows lead to winget uninstalling
> on a seperate install, after using the pc for a while winget fuckin vanished anyway

I kinda worked on that already on the `develop` branch, because it tries to use the `winget --version` command to check if winget is already installed properly, but in some specific cases, the App required to install it, or Winget itself couldn't install automatically, but **MANUALLY**, this solution is done, but not on `main` yet.

**Direct Link >>>** <https://github.com/LeDragoX/Win-Debloat-Tools/archive/develop.zip>

> services fail to start after getting changed by the debloater don't know how or why

It's because a lot of services were **Disabled**, and others set to **Manual**, but the changes only occur when you restart your PC after debloating. Is there any specific service you need `ON`? Btw, you can undo most of the changes by clicking on **Undo Tweaks**

> no contact links either so I couldn't get a community to ask questions

Sorry, it's maintained by me and i don't have a "community" cause that'll lead to several headaches, so i'm just responding through _GitHub_.

> i expected it not to fuck up my pc i dont know how to explain it

It'll not fuck up your PC, just disable a lot of things, and will never mess with "Disable Defender" and other important security features, only harden a bit, at least i can say it's stable enough now to not cause a lot of random BSODs.

> forgive me for being rude
just sick and not wanting to call microsoft support again

It's fine, i expect people to rage on me anytime because of some tweaks or missing stuff 🤣, because that's what a debloater do.

Btw, if something is broken (for real) on your system, i have a tool on GUI to repair the system, just find the **Repair Windows** button on the first tab and wait til' the end. Maybe it helps.

**Comment by LeDragoX** [comment]
The changes were merged (this means you can download from the `main` version), if you need, you can reopen this issue with the last problems

**Comment by LeDragoX** [comment]
I've found the reason winget "uninstalls" every time, it's because it was **never installed**, check #54
