### ISSUE TITLE
Anytime the script runs, `winget is not found` and install with errors

### ISSUE THREAD

**Issue by DED0026** [LeDragoX/Win-Debloat-Tools#54]
### Describe the Bug

![image](https://user-images.githubusercontent.com/98061642/183273703-787bcfa8-b1bb-4622-8a91-8068fead7d9b.png)

### How can this issue be reproduced?

step 1. uninstall winget
step 2. run the debloater

### Expected behavior?

expected behavior should be that app installs without an error.

### Operating System

Windows 10

### Operating System Version

21H2

### Screenshots

![image](https://user-images.githubusercontent.com/98061642/183273814-14898826-c2d2-413c-9309-ae42c0a3cda3.png)
![image](https://user-images.githubusercontent.com/98061642/183273898-4ba91891-e3d7-4534-9e4d-2d2b68d4b504.png)

### Logs

[Win10ScriptGUI_2022-08-06_22-23-11.log](https://github.com/LeDragoX/Win-Debloat-Tools/files/9276120/Win10ScriptGUI_2022-08-06_22-23-11.log)

### Additional Info

i should have mentioned beforehand i run windows to go and i boot from external media
dont know if its really different but versions matter

way to do it is by flashing the official windows 10 iso in windows to go mode
i used rufus, not sure if you can do it any other way
if you chose to do it use mbr partitioning settings

**Comment by LeDragoX** [comment]
### Starting from this point
![](https://user-images.githubusercontent.com/98061642/183273703-787bcfa8-b1bb-4622-8a91-8068fead7d9b.png)

This can only install through command line basically, but couldn't install because of this error:

```ps1
PS>TerminatingError(Invoke-Expression): "Cannot bind argument to parameter 'Command' because it is an empty string."
```

Which felt really strange, but i'll try to fix it again, maybe this happened cause i tried to fix the Winget install when it couldn't install through `Add-AppxPackage`, i found the code line now, so this shouldn't be a problem anymore.

### App installer trying to install itself
![](https://user-images.githubusercontent.com/98061642/183273898-4ba91891-e3d7-4534-9e4d-2d2b68d4b504.png)

At this point, it didn't installed because the App before this one is a requirement, and again, this should be installed through `Add-AppxPackage`, that didn't happen.

> i should have mentioned beforehand i run windows to go and i boot from external media
dont know if its really different but versions matter

> way to do it is by flashing the official windows 10 iso in windows to go mode
i used rufus, not sure if you can do it any other way
if you chose to do it use mbr partitioning settings

This is the first time i see someone using that Rufus feature, lol.

**Now just wait til' i got the fix on the `develop` branch and download it again to test**

**Comment by LeDragoX** [comment]
I think this is Issue has the same problem from #52, the other fix didn't solved this problem.

**Comment by LeDragoX** [comment]
Btw @DED0026, you are not used to GitHub, are you? Because you could **reopen** the other issue with this extra part of the problem, opening more issues with the same problem behaviour don't help.
But you can always add a comment or edit the Issue comment.

I'm not judging you, just giving some tips on GitHub.

**Comment by DED0026** [comment]
> Btw @DED0026, you are not used to GitHub, are you? Because you could **reopen** the other issue with this extra part of the problem, opening more issues with the same problem behavior don't help. But you can always add a comment or edit the Issue comment.
> 
> I'm not judging you, just giving some tips on GitHub.

i dont use github often but i do know how to use it, i thought this issue was somewhat different.
i knew the second error message was a result of the first.
yeah haha, i used rufus because i can install windows on a portable media and boot it from virtually anything.
i will test develop branch on a brand new windows 11 install and my missing winget install just to make sure it works.

**Comment by LeDragoX** [comment]
I forgot to tell beforehand, but you don't need a new install, only if you succeeded on the **Winget install**.

**Comment by weirdal3333** [comment]
If you manually update einget (App Installer) from the Windows store, this issue goes away.

It might have something to do with how it's installed initially. It's a stub, which gets updated with the full version when you use the windows store to do updates.

**Comment by DED0026** [comment]
> I forgot to tell beforehand, but you don't need a new install, only if you succeeded on the **Winget install**.

it worked well on a windows 11 install. i found the issue with my main drive right now
microsoft store thinks it doesnt have permissions to install app installer(code: 0x80070005)
not sure how to solve this but im 70% sure its my fault
i compressed my entire drive with NTFS file compression
just wondering where does microsoft store download packages?

**Comment by DED0026** [comment]
> If you manually update winget (App Installer) from the Windows store, this issue goes away.
> 
> It might have something to do with how it's installed initially. It's a stub, which gets updated with the full version when you use the windows store to do updates.

no
![image](https://user-images.githubusercontent.com/98061642/184090776-44081668-8693-456a-8057-e07d6c01cfe3.png)

**Comment by DED0026** [comment]
> I also don't know what happened with your permissions, but it is nice that you could find the issue.
> 
> About the **Windows Apps** location, i found them on:
> 
> * _C:\Program Files\WindowsApps_

attempts to fix didn't work
issue persists

**Comment by DED0026** [comment]
i believe i know what caused the issue further,
i claimed ownership using the ownership claimer
