### ISSUE TITLE
Remove Cortana completely 

### ISSUE THREAD

**Issue by weirdal3333** [LeDragoX/Win-Debloat-Tools#55]
### Description

I'd like to be able to completely remove Cortana, instead of just disabling it. There is a PowerShell command you can use to do this.

### Reason

Cortana is always running. If it's disabled, the icon remains in the start menu, and you can still open Cortana. It would be nicer if it was just *gone*.

### Examples

Get-AppxPackage -AllUsers Microsoft.549981C3F5F10 | Remove-AppPackage

This command removes Cortana completely. Windows search is a different app and is untouched.

**Comment by LeDragoX** [comment]
**I know that's completely possible**, _i didn't make it before because i didn't saw other scripts doing this_.
There may be someone who wants to use _Cortana_, that's the other reason i've kept it, u know, **for accessibility**.

**Just to address this better, link on MS Store**: <https://www.microsoft.com/store/productId/9NFFX4SZZ23L>

**Comment by LeDragoX** [comment]
I've inserted it on the Tweaks, so this doesn't need to be done "manually", just Apply the Tweaks, then bye Cortana 😉
