### ISSUE TITLE
Check state of particular util in GUI version

### ISSUE THREAD

**Issue by mtkleet** [LeDragoX/Win-Debloat-Tools#60]
### Description

Great tool. Thanks for your effort. One thing that I'm missing and confuses me is lack of clear division between bloatware that's been disabled and active Windows fuctions/services/apps etc. Checkboxes are not showing current state of system. I know it's basically bunch of scripts, not really designed to do this, but i feel like such feature would make things easier - not only for newbies.
 

### Reason

**How will it make things easier for you?**
Remove redundancy when running the script.
**What does it provide that isn't being provided currently?**
Make "interface" more intuituve.
**How does it benefit?**
Larger userbase and overall quality of this tool.

**Comment by LeDragoX** [comment]
I've been running from this issue since i didn't know how to answer properly, because it'll take a lot of effort to check the state of a "tweak" available on a checkbox, or maybe even a software.

The Windows Forms i'm using is an really old library, i had to think what would act like an app "toogle switch button" as are used in modern apps.
If this wasn't a script it would be possible which tweak starts as OFF or ON.
I tried my best to show what has been disable on the system without showing an unknown ID for the user, but showing the proper name of the application or feature.

At least some functions/services/apps may be easier to track, but i don't know if it's worth or not, talking about making the code to do this, because to every new update i make to this script, i will need to have the state being showed on GUI in mind, so since by the real beginning, i thought only to provide the solution, and if the user wants to confirm if its really working, it has to check by itself.
