### ISSUE TITLE
Xbox Game Bar `keyboard + controller shortcuts` aren't working

### ISSUE THREAD

**Issue by apexiptv** [LeDragoX/Win-Debloat-Tools#68]
### Describe the Bug

I'm having issues with the xbox game bar opening when using windows key + G as well as pressing the button on my controller to open it after using Apply tweaks from the win-debloat-tools. I've done an 'undo tweaks' and I have even rolled back using the recovery option. It's something I use so much I can't even imagine not having it as a option. I'd appreciate help on fixing the issue. 

I've reset the gamebar/xbox app, I've uninstalled/reinstalled both of them as well via powershell.  It does not work at all. 

### How can this issue be reproduced?

Just use the apply tweaks... It breaks the listening part of the xbox game bar app for both the controller button press and the win+G button press. If I press the controller button with steam open, the steam app auto triggers big picture mode so I know the controllers functions aren't affected. Just the game bar's ability to listen for the event. 

### Operating System

Windows 10

### Operating System Version

21H2

**Comment by LeDragoX** [comment]
I tried and already know that the you can't re-enable the setting from **Xbox Game Bar** through Windows settings, as it automatically turns off (for some unknown reason).

And even changing on registry the key `UseNexusForGameBarEnabled` from  `HKEY_CURRENT_USER\SOFTWARE\Microsoft\GameBar` to **1** doesn't help anything either, because it auto turns off.

I couldn't find a solution to this situation **yet**, if someone knows and could help, just tell me the steps, and i'll automatize it.

**Comment by LeDragoX** [comment]
I've found the guilty registry key that does disable **Win + G** or **Win + Alt + R**, and... just by deleting this exact key:
```ps1
HKLM\SOFTWARE\Microsoft\PolicyManager\default\ApplicationManagement\AllowGameDVR
```

- You can do this again

![ApplicationFrameHost_3mB8TIGQTR](https://user-images.githubusercontent.com/27643047/203441188-d59d9cf2-0d0f-44d0-9f71-ba7c659cf4b8.gif)

- And this... (Tested with keyboard and emulated Xbox controller w/ DS4Windows)

![ZyO8YiId1V](https://user-images.githubusercontent.com/27643047/203441836-0352bd2a-dade-4401-9a74-f447e9888856.gif)
