### ISSUE TITLE
Removing `My Phone` without prompt and `Game DVR` disabled

### ISSUE THREAD

**Issue by Antonzlo** [LeDragoX/Win-Debloat-Tools#71]
### Describe the Bug

This shouldn't happen, at least not without confirmation. No option to restore it in the app

### How can this issue be reproduced?

1. Click Apply Tweaks

### Expected behavior?

Ask user what to remove

### Operating System

Windows 11

### Operating System Version

21H2

**Comment by LeDragoX** [comment]
Oh, indeed i forgot to put the "**Your Phone**" restorable through the GUI.

Is this the app? Because in the past this wasn't the name: **<https://www.microsoft.com/store/productId/9NMPJ99VJBWV>**

And confirming, the script is intended to run without any prompts, so it can run quickly, then the users can restore or customize what's left or removed as they want.

**Comment by Antonzlo** [comment]
Well, It deleted the Xbox DVR, and it didn't successfully restore it later

**Comment by LeDragoX** [comment]
Sorry, i still need to find out which app does that, so i warn before. By only "applying the tweaks" shouldn't remove that, i'll figure out when i got the time.

And if it was previously removed, the disable/enable checkbox doesn't do anything, only if its still on the system.

**Comment by LeDragoX** [comment]
I've figured out what was disabling **Your Phone** options, i'll send a fix commit on `develop` branch soon...
