### ISSUE TITLE
Xbox Game Bar or NVIDIA game overlay `can't capture video or picture`

### ISSUE THREAD

**Issue by Emiryum** [LeDragoX/Win-Debloat-Tools#98]
### Describe the Bug

ı used this script to make computer use less ram, but after doing so, Game bar Capture and take screenshot options greyed out and nvidia game overlay just wont open
tried restoring the debloat didnt fix it

### How can this issue be reproduced?

by simply running the script  and trying to record screen

### Expected behavior?

to get a script to enable what feature was disabled

### Operating System

Windows 11

### Operating System Version

22H2 22621.1413

### Screenshots

![Screenshot (18)](https://user-images.githubusercontent.com/77542600/227804156-c5791991-d3ef-47cc-b7f9-cb9cf86d5260.png)
![Screenshot (19)](https://user-images.githubusercontent.com/77542600/227804162-20fd44f1-a4af-40b7-a08c-4b372f114781.png)
![Screenshot (21)](https://user-images.githubusercontent.com/77542600/227804165-ed409940-84aa-44d4-ba76-e07d50700985.png)

**Comment by Emiryum** [comment]
fixed it myself  by doing SFC /scannow DDU and reinstalling drivers 
New problem is .exe files takes few minutes to load for setup start 
Any suggestions on that ?

**Comment by LeDragoX** [comment]
Okay, sorry for the delay, most of the things you said indeed happen, cause the script was made in that way.

> Game bar Capture and take screenshot options greyed out

To solve this you can use an option from GUI to re-activate every thing related to Xbox Game Bar

> nvidia game overlay just wont open

The service from NVIDIA is set to Manual, it is written over here how to solve that <https://github.com/LeDragoX/Win-Debloat-Tools#-troubleshooting-known-issues>
(Btw, i'm thinking about not setting it to Manual as each driver update reset the Service status)

> New problem is .exe files takes few minutes to load for setup start

I don't know if this issue is really related to the script or Windows 11 itself, as i recently saw a lot of people reporting which the last update was causing performance issues with SSDs. 
I've found one article, but if you search you can find a lot more about this situation.
<https://www.pcworld.com/article/1663285/windows-11-may-be-slowing-down-your-ssds-again.html>

**Comment by LeDragoX** [comment]
About the Xbox Game bar option, i did forget to show where to find the option.
![image](https://user-images.githubusercontent.com/27643047/229213619-a6fcebcc-1105-46c6-a5c9-5cd829425b56.png)

**Comment by LeDragoX** [comment]
Writting this down, as i'm removing this from README.
- After the update the script will NOT disable or set to Manual any NVIDIA services.

> and Open PowerShell as admin to copy + paste it's content:


### Fix <code>NVIDIA Control Panel</code></summary>

> Only this time (Recommended - Consumes less RAM after boot)

```Powershell
Get-Service "NVDisplay.ContainerLocalSystem" | Set-Service -StartupType Manual -PassThru | Start-Service
Get-Service "NvContainerLocalSystem" | Set-Service -StartupType Manual -PassThru | Start-Service
```

> Permanently (Keeps the service running along with the system)

```Powershell
Get-Service "NVDisplay.ContainerLocalSystem" | Set-Service -StartupType Automatic -PassThru | Start-Service
Get-Service "NvContainerLocalSystem" | Set-Service -StartupType Automatic -PassThru | Start-Service
```
